### ISSUE TITLE
2.5.4 source

### ISSUE THREAD

**Issue by vaskas** [anmipo/keepassb#1]
Hi Andrei, thank you so much for developing KeePassB - it's still an awesome app to use! Really appreciate it that you released the source code. I hope that someone from the community can contribute the KeePass v4 db support and a TOTP generator at some point :wink: I've noticed that the version in bar-descriptor.xml is 2.5.3 while the latest released version of the application is 2.5.4. Is this intentional?

**Comment by anmipo** [comment]
Hi @vaskas, thanks for reaching out! I am glad to hear that KeePassB is still useful :)

> I hope that someone from the community can contribute the KeePass v4 db support and a TOTP generator at some point 😉

This would probably require reviving BB10 dev infrastructure first, so that would be quite a massive undertaking :)

> I've noticed that the version in bar-descriptor.xml is 2.5.3 while the latest released version of the application is 2.5.4. Is this intentional?

I don't think this was intentional... Apparently, the difference between 2.5.3 and 2.5.4 is [this three-letter fix](https://github.com/anmipo/keepassb/commit/c86de18ec34ec6356961aaed0737829391c87e95) for copying extra fields, updated copyright year and increased app version. The "fix" part was merged to master and pushed, but it looks like [release commit](https://github.com/anmipo/keepassb/commit/ab9a87221b61f8171440f591c81a42b13284de28) with copyright year and increased version remained in the development branch. 

I have also found a few changes for the issues I discovered in 2018 while translating KeePassB to KeePassium. They were not even committed, since I don't have my BB dev environment around and cannot test them...  So I just committed them and pushed the whole [`dev` branch](https://github.com/anmipo/keepassb/commits/dev) for history :)

**Comment by vaskas** [comment]
Thanks a lot for the details Andrei! I will give the `dev` branch a try. Who knows we may be able to revive the BB10 scene before it shuts down completely in Jan 22. At least it could be a spectacular finish! Here is some stuff we are working on: https://github.com/BerryTrucks, https://github.com/BerryFarm/berrymuch. There have also been great news on the updated toolchain with GCC 9 - https://didacticode.ca/blog/. You are always welcome back :smiley:
